name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - jeremiah
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Run Tests
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Install ts-node
        run: npm install -g ts-node typescript

      - name: Build
        run: npm run build User_Gallery_Hub -- --configuration production
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_SIGNUP_API: ${{ secrets.FIREBASE_SIGNUP_API }}
          FIREBASE_SIGNIN_API: ${{ secrets.FIREBASE_SIGNIN_API }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          API_URL: ${{ secrets.API_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Only deploy on the main branch

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }} \
            --build-env FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
            --build-env FIREBASE_SIGNUP_API=${{ secrets.FIREBASE_SIGNUP_API }} \
            --build-env FIREBASE_SIGNIN_API=${{ secrets.FIREBASE_SIGNIN_API }} \
            --build-env FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }} \
            --build-env API_URL=${{ secrets.API_URL }}
